import json
from web3 import Web3

# Connect to Ganache
w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:8545"))

# Get accounts
accounts = w3.eth.accounts

# Check if there are accounts available
if not accounts:
        raise Exception("No accounts available in the Ganache instance")

        # Set the default account (use the first account generated by Ganache)
        w3.eth.default_account = accounts[0]

        # Load the compiled contract interface
        with open('Certification.json', 'r') as f:
                contract_interface = json.load(f)

                # Get bytecode and abi
                bytecode = contract_interface['bin']
                abi = contract_interface['abi']

                # Deploy the contract
                Certification = w3.eth.contract(bytecode=bytecode, abi=abi)
                tx_hash = Certification.constructor().transact()
                tx_receipt = w3.eth.waitForTransactionReceipt(tx_hash)

                # Get contract address
                contract_address = tx_receipt.contractAddress
                print(f'Contract deployed at address: {contract_address}')
          
